services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Toumoro\TmQaTools\:
    resource: '../Classes/*'
  
  Toumoro\TmQaTools\Command\RunTestsCommand:
    tags:
      - name: 'console.command'
        command: 'tmqatools:run'
        schedulable: false